version: "3"
services:
  app:
    image: df/django:beta
    stdin_open: true
    tty: true
    command: /bin/bash
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PASS: mysecretpassword
      DB_DATA: doksys
    volumes:
      - ./app:/app
    ports:
      - "5000:80"
    networks:
      - network

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: devguy
      POSTGRES_DB: doksys
    networks:
      - network

  adminer:
    image: adminer:latest
    depends_on:
      - database
    ports:
      - 5001:8080
    networks:
      - network

networks:
  network:
