# http://pythonclub.com.br/configurando-um-servidor-de-producao-para-aplicacoes-python.html
# http://docs.gunicorn.org/en/latest/deploy.html
FROM debian:8
MAINTAINER Diego Feitosa <diegusmiestro@gmail.com>
EXPOSE 8000
RUN apt-get update && apt-get install -y python3 python3-dev python3-pip libpq-dev
RUN mkdir /app && cd /app
COPY ./config/requirements.pip ./
RUN pip3 install -r requirements.pip
RUN django-admin startproject doksys .
WORKDIR /app
CMD ["python3", "manage.py", "runserver"]
