FROM debian:8
MAINTAINER Diego Feitosa <diegusmiestro@gmail.com>
RUN apt-get update && apt-get install -y python3 python3-dev python3-pip libpq-dev
WORKDIR /app
COPY ./requirements.txt /app
RUN pip3 install -r requirements.txt
