version: "3"
services:
  django:
    image: doksys:django
    volumes:
      - ./app:/app
    ports:
      - "80:80"
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - interna
networks:
  interna:
