version: "3"
services:
  django:
    image: django-dev:alpha
    volumes:
      - ./app:/app
    ports:
      - "80:80"
      - "8000:8000"
    deploy:
      mode: global
    networks:
      - interna
networks:
  interna:
